### PR TITLE
#163740001 Delete Meetup  using User Interface (UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Allows an admin user do delete meetup from questioner
### What are the tasks to be completed?
* Consume Questioner API to allow deletion of meetup via UI
* Ensure user experience is not compromised
* Ensure API responses are correctly captured and rendered as feedback to the user
### How should this be manually tested?
After cloning the repo:
* ` git checkout ft-delete-meetup-163740001`
*  Using a web browser, launch the meetups.html file, click Admin Panel button then delete meetups or create if there is none,
### Screenshots
screenshot from 2019-02-06 15-30-00
screenshot from 2019-02-06 15-30-12
screenshot from 2019-02-06 15-30-16
### What are the relevant pivotal tracker stories?
[#163740001](https://www.pivotaltracker.com/story/show/163740001)

### CODE REVIEW

**Comment by ceexon** [comment]
if its hosted 
I need the admin password :joy: :joy_cat:

**Comment by Ogutu-Brian** [comment]
> if its hosted
> I need the admin password
@kburudi once I merge you will be able to do that. The email is:
`admin@gmail.com` and the password is `password12#B`

**Comment by Ogutu-Brian** [comment]
@kburudi , you can now do that, Here is the link [Questioner](https://ogutu-brian.github.io/Questioner/UI/)

**Comment by wathigo** [comment]
Good work @Ogutu-Brian

**Comment by a-braham** [comment]
Awesome job man..

**Comment by Ogutu-Brian** [comment]
> Good work @Ogutu-Brian

Thanks @wathigo

**Comment by Ogutu-Brian** [comment]
> Awesome job man..

Thanks @a-braham

**Pull request merged**
