### PR TITLE
#162969216 Landing page for Questioner (UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a simple but detailed and responsive landing page for Questioner   
### Description of tasks to be completed
Have the following achieved
1. Simple landing page
2. Informative landing page
3. Responsive landing page

### How should this be manually tested?
After cloning the repo, cd into it then cdd into UI and click on index.html file
### Additional background context
The image used is open source and can be found from this [link](https://www.google.com/search?q=meeting+open+source+images&tbm=isch&tbo=u&source=univ&sa=X&ved=2ahUKEwjsxdaY49LfAhVN5eAKHZcEDdYQsAR6BAgFEAE&biw=1366&bih=590#imgrc=kDa2YbqS0UJMhM:
)   
### Screenshots
screenshot from 2019-01-04 02-57-47
screenshot from 2019-01-04 02-58-15
### What are the relevant pivotal tracker stories?
[#162969216](https://www.pivotaltracker.com/story/show/162969216)

### CODE REVIEW

**Comment by gik-hub** [comment]
Great work

**Comment by Ogutu-Brian** [comment]
> Great work
Thanks @TgeeT

**Review by Ogollah — COMMENTED** [review]
Great work, but you need a new line at the end of the file

**Comment by Ogutu-Brian** [comment]
What do you mean by new line at the end of the file @Ogollah ?

**Pull request merged**
